### ISSUE TITLE
IsCanceled crash with 6.15.1

### ISSUE THREAD

**Issue by pepone** [mxcl/PromiseKit#1214]
After updating to 6.15.1 I seeing crashes when a promise is rejected seeing this

```
catching exact types with AMI mapping... 2021-05-26 16:09:01.409 TestDriver[42514:211941] *** NSForwarding: warning: object 0x7fa78e50c7c0 of class 'IceExceptions.A' does not implement methodSignatureForSelector: -- trouble ahead
Unrecognized selector -[IceExceptions.A valueForKey:]
```

`IceExceptions.A` is the error used to reject the promise which is a class that implements `Error` protocol derived from our custom `UserException` https://github.com/zeroc-ice/ice/blob/f3da3aa5acb3b70d6662472e97e1954331c6aadf/swift/src/Ice/Exception.swift#L47

```
* frame #7: 0x000000010c380c71 PromiseKit`Error.isCancelled.getter(self=<unavailable>) at Error.swift:92:47 [opt]
    frame #8: 0x000000010c36d24b PromiseKit`closure #1 in CatchMixin.catch($0=<unavailable>, policy=<unavailable>, on=0x000000010c48a080, flags=nil, body=0x000000010c5dfab0 IceExceptions`partial apply forwarder for closure #3 (Swift.Error) -> () in closure #3 (PromiseKit.Resolver<()>) -> () in IceExceptions.allTests(TestCommon.TestHelper) throws -> IceExceptions.ThrowerPrx at <compiler-generated>, finalizer=0x000060000276b960) at Catchable.swift:29:44 [opt]
    frame #9: 0x000000010c3709b3 PromiseKit`partial apply for closure #1 in CatchMixin.catch(on:flags:policy:_:) at <compiler-generated>:0 [opt]
    frame #10: 0x000000010c373fdc PromiseKit`thunk for @escaping @callee_guaranteed (@in_guaranteed A) -> () at <compiler-generated>:0 [opt]
    frame #11: 0x000000010c373a35 PromiseKit`partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed A) -> () at <compiler-generated>:0 [opt]
    frame #12: 0x000000010c373a11 PromiseKit`partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed A) -> (@out ()) [inlined] reabstraction thunk helper <τ_0_0> from @escaping @callee_guaranteed (@in_guaranteed τ_0_0) -> (@out ()) to @escaping @callee_guaranteed (@in_guaranteed τ_0_0) -> () at <compiler-generated>:0 [opt]
    frame #13: 0x000000010c373a0e PromiseKit`partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed A) -> (@out ()) at <compiler-generated>:0 [opt]
    frame #14: 0x000000010c373943 PromiseKit`partial apply for closure #2 in EmptyBox.seal(_:) [inlined] closure #2 ($0=0x0000000000000000, value=<unavailable>) -> ()) -> () in PromiseKit.EmptyBox.seal(τ_0_0) -> () at Box.swift:51:38 [opt]
    frame #15: 0x000000010c37393e PromiseKit`partial apply for closure #2 in EmptyBox.seal(_:) at <compiler-generated>:0 [opt]
    frame #16: 0x000000010c3739c0 PromiseKit`partial apply for thunk for @callee_guaranteed (@guaranteed @escaping @callee_guaranteed @substituted <A> (@in_guaranteed A) -> () for <A>) -> (@error @owned Error) [inlined] reabstraction thunk helper <τ_0_0> from @callee_guaranteed (@guaranteed @escaping @callee_guaranteed @substituted <τ_0_0> (@in_guaranteed τ_0_0) -> () for <τ_0_0>) -> (@error @owned Swift.Error) to @escaping @callee_guaranteed (@in_guaranteed @escaping @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> (@out τ_0_1) for <τ_0_0()>) -> (@error @owned Swift.Error) at <compiler-generated>:0 [opt]
    frame #17: 0x000000010c373977 PromiseKit`partial apply for thunk for @callee_guaranteed (@guaranteed @escaping @callee_guaranteed @substituted <A> (@in_guaranteed A) -> () for <A>) -> (@error @owned Error) at <compiler-generated>:0 [opt]
    frame #18: 0x00007fff2c9911b4 libswiftCore.dylib`Swift.Sequence.forEach((τ_0_0.Element) throws -> ()) throws -> () + 436
    frame #19: 0x000000010c372305 PromiseKit`EmptyBox.seal(value=<unavailable>, self=<unavailable>) at Box.swift:51:29 [opt]
    frame #20: 0x000000010c36616c PromiseKit`closure #1 in Thenable.map<Self>($0=<unavailable>, on=0x000000010c48a080, flags=nil, rp=(box = 0x000060000276b930), transform=0x000000010c5dfa40 IceExceptions`reabstraction thunk helper from @escaping @callee_guaranteed () -> (@error @owned Swift.Error) to @escaping @callee_guaranteed (@in_guaranteed ()) -> (@out (), @error @owned Swift.Error)partial apply forwarder with unmangled suffix ".247" at <compiler-generated>) at Thenable.swift:84:24 [opt]
    frame #21: 0x000000010c36a909 PromiseKit`partial apply for closure #1 in Thenable.map<A>(on:flags:_:) at <compiler-generated>:0 [opt]
    frame #22: 0x000000010c373fdc PromiseKit`thunk for @escaping @callee_guaranteed (@in_guaranteed A) -> () at <compiler-generated>:0 [opt]
    frame #23: 0x000000010c373a35 PromiseKit`partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed A) -> () at <compiler-generated>:0 [opt]
    frame #24: 0x000000010c373a11 PromiseKit`partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed A) -> (@out ()) [inlined] reabstraction thunk helper <τ_0_0> from @escaping @callee_guaranteed (@in_guaranteed τ_0_0) -> (@out ()) to @escaping @callee_guaranteed (@in_guaranteed τ_0_0) -> () at <compiler-generated>:0 [opt]
    frame #25: 0x000000010c373a0e PromiseKit`partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed A) -> (@out ()) at <compiler-generated>:0 [opt]
    frame #26: 0x000000010c373943 PromiseKit`partial apply for closure #2 in EmptyBox.seal(_:) [inlined] closure #2 ($0=0x0000000000000000, value=<unavailable>) -> ()) -> () in PromiseKit.EmptyBox.seal(τ_0_0) -> () at Box.swift:51:38 [opt]
    frame #27: 0x000000010c37393e PromiseKit`partial apply for closure #2 in EmptyBox.seal(_:) at <compiler-generated>:0 [opt]
    frame #28: 0x000000010c3739c0 PromiseKit`partial apply for thunk for @callee_guaranteed (@guaranteed @escaping @callee_guaranteed @substituted <A> (@in_guaranteed A) -> () for <A>) -> (@error @owned Error) [inlined] reabstraction thunk helper <τ_0_0> from @callee_guaranteed (@guaranteed @escaping @callee_guaranteed @substituted <τ_0_0> (@in_guaranteed τ_0_0) -> () for <τ_0_0>) -> (@error @owned Swift.Error) to @escaping @callee_guaranteed (@in_guaranteed @escaping @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> (@out τ_0_1) for <τ_0_0()>) -> (@error @owned Swift.Error) at <compiler-generated>:0 [opt]
    frame #29: 0x000000010c373977 PromiseKit`partial apply for thunk for @callee_guaranteed (@guaranteed @escaping @callee_guaranteed @substituted <A> (@in_guaranteed A) -> () for <A>) -> (@error @owned Error) at <compiler-generated>:0 [opt]
    frame #30: 0x00007fff2c9911b4 libswiftCore.dylib`Swift.Sequence.forEach((τ_0_0.Element) throws -> ()) throws -> () + 436
    frame #31: 0x000000010c372305 PromiseKit`EmptyBox.seal(value=<unavailable>, self=<unavailable>) at Box.swift:51:29 [opt]
    frame #32: 0x000000010c3651e2 PromiseKit`partial apply for implicit closure #2 in implicit closure #1 in firstly<U>(execute:) [inlined] implicit closure #2 (argument=<unavailable>, self=0x000060000276b7e0) -> () in implicit closure #1 (PromiseKit.Box<PromiseKit.Result<τ_0_0.T>>) -> (PromiseKit.Result<τ_0_0.T>) -> () in PromiseKit.firstly<τ_0_0 where τ_0_0: PromiseKit.Thenable>(execute: () throws -> τ_0_0) -> PromiseKit.Promise<τ_0_0.T> at firstly.swift:29:36 [opt]
    frame #33: 0x000000010c3651db PromiseKit`partial apply for implicit closure #2 in implicit closure #1 in firstly<A>(execute:) at <compiler-generated>:0 [opt]
    frame #34: 0x000000010c373fdc PromiseKit`thunk for @escaping @callee_guaranteed (@in_guaranteed A) -> () at <compiler-generated>:0 [opt]
    frame #35: 0x000000010c373a35 PromiseKit`partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed A) -> () at <compiler-generated>:0 [opt]
    frame #36: 0x000000010c373a11 PromiseKit`partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed A) -> (@out ()) [inlined] reabstraction thunk helper <τ_0_0> from @escaping @callee_guaranteed (@in_guaranteed τ_0_0) -> (@out ()) to @escaping @callee_guaranteed (@in_guaranteed τ_0_0) -> () at <compiler-generated>:0 [opt]
    frame #37: 0x000000010c373a0e PromiseKit`partial apply for thunk for @escaping @callee_guaranteed (@in_guaranteed A) -> (@out ()) at <compiler-generated>:0 [opt]
    frame #38: 0x000000010c373943 PromiseKit`partial apply for closure #2 in EmptyBox.seal(_:) [inlined] closure #2 ($0=0x0000000000000000, value=<unavailable>) -> ()) -> () in PromiseKit.EmptyBox.seal(τ_0_0) -> () at Box.swift:51:38 [opt]
    frame #39: 0x000000010c37393e PromiseKit`partial apply for closure #2 in EmptyBox.seal(_:) at <compiler-generated>:0 [opt]
    frame #40: 0x000000010c3739c0 PromiseKit`partial apply for thunk for @callee_guaranteed (@guaranteed @escaping @callee_guaranteed @substituted <A> (@in_guaranteed A) -> () for <A>) -> (@error @owned Error) [inlined] reabstraction thunk helper <τ_0_0> from @callee_guaranteed (@guaranteed @escaping @callee_guaranteed @substituted <τ_0_0> (@in_guaranteed τ_0_0) -> () for <τ_0_0>) -> (@error @owned Swift.Error) to @escaping @callee_guaranteed (@in_guaranteed @escaping @callee_guaranteed @substituted <τ_0_0, τ_0_1> (@in_guaranteed τ_0_0) -> (@out τ_0_1) for <τ_0_0()>) -> (@error @owned Swift.Error) at <compiler-generated>:0 [opt]
    frame #41: 0x000000010c373977 PromiseKit`partial apply for thunk for @callee_guaranteed (@guaranteed @escaping @callee_guaranteed @substituted <A> (@in_guaranteed A) -> () for <A>) -> (@error @owned Error) at <compiler-generated>:0 [opt]
    frame #42: 0x00007fff2c9911b4 libswiftCore.dylib`Swift.Sequence.forEach((τ_0_0.Element) throws -> ()) throws -> () + 436
    frame #43: 0x000000010c372305 PromiseKit`EmptyBox.seal(value=<unavailable>, self=<unavailable>) at Box.swift:51:29 [opt]
    frame #44: 0x000000010c362464 PromiseKit`Resolver.reject(error=(error = 0x0000600000a28820), self=<unavailable>) at Resolver.swift:24:13 [opt]
    frame #45: 0x0000000108ea75d0 Ice`closure #1 in closure #1 in ObjectPrxI._invokeAsync(ok=false, bytes=0x6000016242e3, count=21, self=0x0000600002776250, userException=some, seal=(box = 0x000060000276b9f0)) at Proxy.swift:1289:49
```

**Comment by dtaylor1701** [comment]
👋  I have a fix in this PR: https://github.com/mxcl/PromiseKit/pull/1215

**Comment by mxcl** [comment]
Releasing: https://github.com/mxcl/PromiseKit/actions/runs/883353524
