### PR TITLE
Fix build on Xcode 9.3

### PR DESCRIPTION
**Pull request by nikolaykasyanov**
It looks like Clang no longer allows object subscripting on id&lt;protocols&gt; if neither of protocols defines -objectForKeyedSubscript:.

### CODE REVIEW

**Comment by mxcl** [comment]
CI says we build on Xcode 9.3 already.

**Comment by nikolaykasyanov** [comment]
@mxcl legacy-1.x branch [doesn't](https://github.com/mxcl/PromiseKit/blob/ba8dfca5e597c5930dc1e60b15c9d80456cdecc3/.travis.yml) though.

[A similar code](https://github.com/mxcl/PromiseKit/blob/81633ff9a4a58e3bb020487e7786e51831f73295/Sources/when.m#L62) in master defines `id promises`, hence no compilation error.

**Comment by mxcl** [comment]
Oh, ok. Sorry didn't see the branch you were merging into and since you didn't specify I assumed we were talking about the latest version.

**Comment by nikolaykasyanov** [comment]
@mxcl thanks! Sorry for confusion.

**Comment by nikolaykasyanov** [comment]
@mxcl would you be so kind to push 1.7.6 to CocoaPods?

**Comment by mxcl** [comment]
Ugh, CocoaPods is so tedious. Coming up.
