### ISSUE TITLE
Implicit declaration of function 'assert' is invalid in C99

### ISSUE THREAD

**Issue by RohitKumarAgarwalla** [mxcl/PromiseKit#1091]
When upgrading from PromiseKit 4.5.0 to 6.8.4, we are always getting an error in NSURLSession+AnyPromise.m file.

![image](https://user-images.githubusercontent.com/35230439/63487471-07369900-c4c9-11e9-8a37-a9adbf70e765.png)

Please let me know if anything specific needs to be changed in my project configuration.

**Comment by mxcl** [comment]
You probably have warnings as errors on for all targets, which will cause this sort of problem in general. Though ofc. we shouldn't warn. I'll take a look.

**Comment by RohitKumarAgarwalla** [comment]
I am not having warnings as errors for any of the targets in my application.

![Screenshot 2019-08-23 at 11 38 05 AM](https://user-images.githubusercontent.com/35230439/63573723-b5167600-c5a3-11e9-9414-7c354850eb57.png)

Any other reason that these might be happening. 
We are using Swift 4.2

**Comment by RomanPodymov** [comment]
Hello @RohitKumarAgarwalla 
How do you install PromiseKit? I cannot reproduce this issue in Xcode 12.0.1.
